### PR TITLE
Draft: maintenance: adding automated testing through GH actions

### PR DESCRIPTION
**Pull request by chakravarthik27**
## Checklist:

- [ ] I've added Google style docstrings to my code.
- [ ] I've used `pydantic` for typing when/where necessary.
- [ ] I have linted my code
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by luca-martial — APPROVED** [review]

**Comment by luca-martial** [comment]
@chakravarthik27 you want to merge once the other GH issues are completed? I think we can merge now. What do you think?

**Comment by luca-martial** [comment]
@alytarik will take care of conflicts - please also make sure that the badge on the readme looks good after we merge this

**Comment by luca-martial** [comment]
@chakravarthik27 let's do the pkl file option in another PR. I will delete them for now

**Comment by chakravarthik27** [comment]
Ok, no worries..

**Pull request merged**
