### PR TITLE
fix: alignment `add_contraction`

### PR DESCRIPTION
**Pull request by JulesBelveze**
This PR aims at solving #305 

## Checklist:

- [x] I've added Google style docstrings to my code.
- [x] I've used `pydantic` for typing when/where necessary.
- [x] I have linted my code
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by JulesBelveze** [comment]
@ArshaanNazir @luca-martial feel free to merge if it looks good to you

**Review by luca-martial — APPROVED** [review]
Thank you @JulesBelveze! LGTM

**Review by luca-martial — CHANGES_REQUESTED** [review]
@JulesBelveze the tests failed, it looks like add_contraction tests works fine now, but getting an error for the other tests. We're also waiting for https://github.com/JohnSnowLabs/nlptest/pull/325 to be merged before merging yours

**Review by luca-martial — APPROVED** [review]

**Comment by luca-martial** [comment]
Whatever issues may come out of this, we will attack in the refactoring branch

**Pull request merged**
