### PR TITLE
Update/docs for summarization

### PR DESCRIPTION
**Pull request by Prikshit7766**
## Checklist:
- [ ] updated documentation for the summarization

### CODE REVIEW

**Review by ArshaanNazir — COMMENTED** [review]
update requirements file

**Comment by Prikshit7766** [comment]
> update requirements file

**Comment by Prikshit7766** [comment]
are you reffering to  Gemfile.lock

**Review by ArshaanNazir — COMMENTED** [review]
Also remove question-answering from supported tasks in label representation task ( both proportion and count one) and for bias tests add QA and summarization in supported tasks @Prikshit7766

**Comment by Prikshit7766** [comment]
@ArshaanNazir 
should i only  remove question-answering from supported tasks in label representation task or summarization too

**Comment by ArshaanNazir** [comment]
> should i only remove question-answering from supported tasks in label representation task or summarization too

Remove it from label representation supported tests only.

**Comment by Prikshit7766** [comment]
If there are any changes required, please let me know.

**Comment by ArshaanNazir** [comment]
> If there are any changes required, please let me know.

from label representation, remove summarization as well

**Pull request merged**
