### PR TITLE
Refacto: codebase clean up

### PR DESCRIPTION
**Pull request by JulesBelveze**
This PR aims at tackling #194 

## Checklist:

- [ ] I've added Google style docstrings to my code.
- [ ] I've used `pydantic` for typing when/where necessary.
- [ ] I have linted my code
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by JulesBelveze** [comment]
@chakravarthik27 @luca-martial I've added a test for the `India  -> United States` entity swap, seems to work now.

**Review by JulesBelveze — COMMENTED** [review]
@luca-martial @ArshaanNazir @chakravarthik27 guys I'm having a bit of an existential doubt here.
Do you think it might make sense to have a base class `Sample` that we then extend for specific task (e.g. `NERSample`)? Because there are a bunch of methods that are only relevant to the NER task...

**Comment by luca-martial** [comment]
> @luca-martial @ArshaanNazir @chakravarthik27 guys I'm having a bit of an existential doubt here.
> 
> Do you think it might make sense to have a base class `Sample` that we then extend for specific task (e.g. `NERSample`)? Because there are a bunch of methods that are only relevant to the NER task...

Yes it's been discussed before - we just put it off because it works for now, but if you want to go for it right now, I dont see any reason against it, except that it might take time away from the rest of your refactoring tasks. Up to you!

**Comment by luca-martial** [comment]
@chakravarthik27 this is almost ready to merge, just need to resolve the conflicts

**Comment by chakravarthik27** [comment]
@luca-martial , @JulesBelveze 
please check it, I resolved the conflicts from release/1.0.0 branch

**Comment by JulesBelveze** [comment]
Don't have access to my laptop this weekend and it's quite tricky to review on the phone.. can I leave it to you @luca-martial ?

**Review by luca-martial — APPROVED** [review]

**Comment by luca-martial** [comment]
I reverted because of issues affecting augmentation

**Pull request merged**
