### PR TITLE
Fix/remove cohyphonym test

### LINKED ISSUE #310: Remove swap cohyponym test along with dependencies

### PR DESCRIPTION
**Pull request by alytarik**
## Checklist:

- [x] I've added Google style docstrings to my code.
- [x] I've used `pydantic` for typing when/where necessary.
- [x] I have linted my code
- [x] I have added tests to cover my changes.

fixes #310

### CODE REVIEW

**Comment by luca-martial** [comment]
@alytarik you're not done with this one yet right?

**Comment by alytarik** [comment]
> @alytarik you're not done with this one yet right?

I am done, I was waiting the build tests and then forgot to request a review :)

**Comment by luca-martial** [comment]
> > @alytarik you're not done with this one yet right?
> 
> I am done, I was waiting the build tests and then forgot to request a review :)

Sounds good, do you want to try to resolve the conflict?

**Comment by alytarik** [comment]
> > > @alytarik you're not done with this one yet right?
> > 
> > I am done, I was waiting the build tests and then forgot to request a review :)
> 
> Sounds good, do you want to try to resolve the conflict?

I am outside, I can check tomorrow morning or you can go ahead

**Comment by luca-martial** [comment]
No problem, you can take care of it tomorrow, I'm here to help if you face any issues 😃

**Review by luca-martial — APPROVED** [review]
Thanks @alytarik 🎸

**Pull request merged**
